### ISSUE TITLE
Intermittent SqlAlchemy OperationalError raised on Heroku Postgresql hobby-dev plan 

### ISSUE THREAD

**Issue by smallwat3r** [smallwat3r/shhh#172]
Noticed some rare intermittent `sqlalchemy.exc.OperationalError` errors happening when Shhh is using Heroku Postgresql hobby-dev plan as a primary DB.

I suspect this to be due to the DB going asleep as this is a free plan. After a few tries, the DB seems to be waking up and once the first DB operation succeed, the next DB operations seems to all be working. I suppose the DB goes back to sleep after a while, so the same process might start again.

The downtime can easily be noticed when rebooting the Heroku Shhh app or the DB.

What's weird is that the retry mechanism on Shhh (both from the UI and from the server), that was added to automatically wake up the DB when this happens, doesn't seems to fix it anymore.

Traceback of the issue from Heroku:
```
2021-05-13T23:04:24.023816+00:00 app[web.1]: Traceback (most recent call last):
2021-05-13T23:04:24.023818+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
2021-05-13T23:04:24.023818+00:00 app[web.1]: self.dialect.do_execute(
2021-05-13T23:04:24.023819+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
2021-05-13T23:04:24.023819+00:00 app[web.1]: cursor.execute(statement, parameters)
2021-05-13T23:04:24.023820+00:00 app[web.1]: psycopg2.OperationalError: SSL SYSCALL error: EOF detected
2021-05-13T23:04:24.023821+00:00 app[web.1]: 
2021-05-13T23:04:24.023821+00:00 app[web.1]: 
2021-05-13T23:04:24.023821+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2021-05-13T23:04:24.023822+00:00 app[web.1]: 
2021-05-13T23:04:24.023822+00:00 app[web.1]: Traceback (most recent call last):
2021-05-13T23:04:24.023823+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
2021-05-13T23:04:24.023823+00:00 app[web.1]: response = self.full_dispatch_request()
2021-05-13T23:04:24.023823+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
2021-05-13T23:04:24.023824+00:00 app[web.1]: rv = self.handle_user_exception(e)
2021-05-13T23:04:24.023824+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
2021-05-13T23:04:24.023824+00:00 app[web.1]: rv = self.dispatch_request()
2021-05-13T23:04:24.023825+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
2021-05-13T23:04:24.023825+00:00 app[web.1]: return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2021-05-13T23:04:24.023826+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/views.py", line 83, in view
2021-05-13T23:04:24.023826+00:00 app[web.1]: return self.dispatch_request(*args, **kwargs)
2021-05-13T23:04:24.023827+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/flask/views.py", line 157, in dispatch_request
2021-05-13T23:04:24.023827+00:00 app[web.1]: return meth(*args, **kwargs)
2021-05-13T23:04:24.023827+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/webargs/core.py", line 450, in wrapper
2021-05-13T23:04:24.023828+00:00 app[web.1]: return func(*args, **kwargs)
2021-05-13T23:04:24.023828+00:00 app[web.1]: File "/app/shhh/api/api.py", line 67, in get
2021-05-13T23:04:24.023828+00:00 app[web.1]: response, code = read_secret(slug, passphrase)
2021-05-13T23:04:24.023829+00:00 app[web.1]: File "/app/shhh/api/handlers.py", line 79, in read_secret
2021-05-13T23:04:24.023829+00:00 app[web.1]: secret = Entries.query.filter_by(slug_link=slug).first()
2021-05-13T23:04:24.023829+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2750, in first
2021-05-13T23:04:24.023830+00:00 app[web.1]: return self.limit(1)._iter().first()
2021-05-13T23:04:24.023830+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2834, in _iter
2021-05-13T23:04:24.023831+00:00 app[web.1]: result = self.session.execute(
2021-05-13T23:04:24.023831+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1677, in execute
2021-05-13T23:04:24.023831+00:00 app[web.1]: result = conn._execute_20(statement, params or {}, execution_options)
2021-05-13T23:04:24.023832+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
2021-05-13T23:04:24.023832+00:00 app[web.1]: return meth(self, args_10style, kwargs_10style, execution_options)
2021-05-13T23:04:24.023833+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 329, in _execute_on_connection
2021-05-13T23:04:24.023833+00:00 app[web.1]: return connection._execute_clauseelement(
2021-05-13T23:04:24.023833+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
2021-05-13T23:04:24.023834+00:00 app[web.1]: ret = self._execute_context(
2021-05-13T23:04:24.023834+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
2021-05-13T23:04:24.023834+00:00 app[web.1]: self._handle_dbapi_exception(
2021-05-13T23:04:24.023835+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
2021-05-13T23:04:24.023835+00:00 app[web.1]: util.raise_(
2021-05-13T23:04:24.023836+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
2021-05-13T23:04:24.023836+00:00 app[web.1]: raise exception
2021-05-13T23:04:24.023836+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
2021-05-13T23:04:24.023837+00:00 app[web.1]: self.dialect.do_execute(
2021-05-13T23:04:24.023837+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
2021-05-13T23:04:24.023837+00:00 app[web.1]: cursor.execute(statement, parameters)
2021-05-13T23:04:24.023838+00:00 app[web.1]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected
```

**Comment by smallwat3r** [comment]
Should be fixed with #173 so will close this issue for now.
